version: "3.8"

services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    restart: unless-stopped
    ports:
      - "9000:9000"  # HTTP interface
      - "9009:9009"  # QuestDB Line Protocol
      - "8812:8812"  # PostgreSQL wire protocol
    volumes:
      - questdb_data:/var/lib/questdb
    environment:
      - QDB_PG_PORT=8812
      - QDB_HTTP_PORT=9000
      - QDB_LINE_TCP_PORT=9009
      - QDB_LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  questdb_data:
